version: "2.1"

services:
    db_check:
        image: jwilder/dockerize
        command: dockerize -wait tcp://db:3306 -timeout 120s
        links:
            - db

    migration:
        build: db/
        links:
            - db
        environment:
            LIQUIBASE_USERNAME: root
            LIQUIBASE_PASSWORD: ""
            LIQUIBASE_URL: jdbc:mysql://db/service
